FROM ubuntu:22.04

ARG CRAC_JDK_URL

ENV JAVA_HOME /opt/jdk
ENV PATH $JAVA_HOME/bin:/opt/gradle/bin:$PATH
ENV CRAC_FILES_DIR /opt/crac-files
ENV GRADLE_OPTS -Dorg.gradle.project.buildDir=/tmp/gradle-build

RUN export DEBIAN_FRONTEND=noninteractive && apt-get update && apt-get -y install tzdata ca-certificates git curl nano hey libarchive-tools && rm -rf /var/lib/apt/lists/*

ADD $CRAC_JDK_URL $JAVA_HOME/openjdk.tar.gz
RUN tar --extract --file $JAVA_HOME/openjdk.tar.gz --directory "$JAVA_HOME" --strip-components 1; rm $JAVA_HOME/openjdk.tar.gz;

RUN mkdir -p /opt/gradle && cd /opt/gradle && curl -L "https://services.gradle.org/distributions/gradle-8.5-bin.zip" | bsdtar --strip-components=1 -xvf- && chmod +x /opt/gradle/bin/gradle

RUN mkdir -p /workspace
RUN git config --global --add safe.directory /workspace

ENTRYPOINT /bin/bash
