FROM bellsoft/liberica-openjdk-debian:21.0.1-cds as build
COPY . /data/
RUN apt-get install --no-install-recommends -y unzip
RUN cd /data && ./jarexe.sh -b

FROM bellsoft/liberica-openjdk-debian:21.0.1-cds
COPY --from=build /data/build/libs /data/build/libs
COPY src/scripts/entrypoint-jarexe.sh /data/entrypoint.sh

ENTRYPOINT /data/entrypoint.sh